apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: item-inventory
  name: finn10-item-inventory-app
  namespace: openshift-gitops
spec:
  destination:
    namespace: finn10
    server: https://kubernetes.default.svc
  project: finn10
  source:
    path: lab3-4/apps/item-inventory/overlays
    repoURL: https://github.com/glenchristian/eda-tech-academy.git
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

